plugins(({
    id 'java'
    id 'org.springframework.boot' version '4.1.0-M4'
    id 'io.spring.dependency-management' version '1.1.7' //It manages versions of spring modules, so that we don't need to worry about version compatibility
}))

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    //Spring
    implementation 'org.springframework.boot:spring-boot-starter:4.0.5' //Spring-boot starters - just jar dependencies, which add zhe needed functionalities with autoconfiguration for certain module
    implementation 'org.springframework.boot:spring-boot-starter-test'

    //Postgres
    implementation 'org.postgresql:postgresql'

    //Lombok
    compileOnly("org.projectlombok:lombok:1.18.44")
    annotationProcessor("org.projectlombok:lombok:1.18.44")
    testCompileOnly("org.projectlombok:lombok:1.18.44")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.44")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}