#https://docs.spring.io/spring-boot/reference/features/external-config.html
#there are 14 ways to configure properties and each one is overriding the previous one
db.username=aleksandramialton
db.password=root
db.poolsize=12
db.driver=postgresDriver
db.url=postgres:5432
db.host=localhost,127.0.0.1

# to switch between environments we can configure additional property files with overwritten properties (see application-qa.properties)

# as alternative to properties we can use yml files - is used in modern applications, because it has a tree hierarchy