# we have added --spring.profiles.active=qa into "programm arguments" in the Run->Edit Configurations...
db.username=mssql-${db.poolsize}
# the output would be mssql-12 because poolsize in application.properties is 12
